### ISSUE TITLE
Annotated genes‘ type is wrong

### ISSUE THREAD

**Issue by Zefeng-Wu** [hfang-bristol/dnet#1]
Hi there, 
i am running dnet to calculate the similarities among  some genes which have been annotated to different GO terms by using the function of “dDAGannotate”.  However, it throw an error with" sort(as.numeric(unique(unlist(anno)))): error". I checked the codes of  "dDAGgeneSim"  and found there may be the force action for genes to convert to be numeric type, so i suggest to  update this shortcomings.

**Comment by hfang-bristol** [comment]
Hi Zefeng-Wu

The function requires providing genes as 'Entrez gene id' (rather than gene symbols). Please refer to the content of genes in the step 4) below.

# 1) load HPPA as igraph object
ig.HPPA <-dRDataLoader(RData='ig.HPPA')
g <- ig.HPPA
# 2) load human genes annotated by HPPA
org.Hs.egHPPA <- dRDataLoader(RData='org.Hs.egHPPA')
# 3) prepare for ontology and its annotation information 
dag <- dDAGannotate(g, annotations=org.Hs.egHPPA, path.mode="all_paths", verbose=TRUE)
# 4) calculate pair-wise semantic similarity between 5 randomly chosen genes 
allgenes <- unique(unlist(V(dag)$annotations))
genes <- sample(allgenes,5)
sim <- dDAGgeneSim(g=dag, genes=genes, method.gene="BM.average", method.term="Resnik", parallel=FALSE, verbose=TRUE)
sim

**Comment by Zefeng-Wu** [comment]
OK,  thanks a lot.
